
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: JOJOmoney_development

  
  <<: *default
  database: JOJOmoney_test


production:
  <<: *default
  database: JOJOmoney_production
  username: JOJOmoney
  password: <%= ENV['JOJOMONEY_DATABASE_PASSWORD'] %>
